### ISSUE TITLE
[Request] Script to check for missing translations in a locale

### ISSUE THREAD

**Issue by FjorgeTheHuman** [arch-community/qbot#221]
A script which checks a locale against `en` for missing or extra translations to make maintaining locales a little easier

**Comment by anna328p** [comment]
good idea, should be straightforward enough

**Comment by anna328p** [comment]
it wasn't

**Comment by anna328p** [comment]
![image](https://user-images.githubusercontent.com/9790772/193478607-14a4b0b6-923b-41e9-8133-798224c52b2e.png)

**Comment by anna328p** [comment]
um

**Comment by FjorgeTheHuman** [comment]
looking at that is painful. wtf???
