### ISSUE TITLE
Invalid regex in the blacklist causes it not to work entirely.

### ISSUE THREAD

**Issue by fdsfafsasafsasaasa** [arch-community/qbot#63]
**Steps to reproduce**:

1. Add invalid regex to the blacklist command (`.bl`).
2. Send a message with blacklisted text in it.  

**Expected result**:

`Qbot` deletes the message.

**Actual result:**

Nothing happens, on the user side.

**Comment by thewarsawpakt** [comment]
https://discord.com/channels/808502463798968331/808502464420118531/825193279876366376
Finally got around to this.
