### ISSUE TITLE
[Feature request] Accept extra operands when making the bot doing search on Arch wiki, and then giving the output to the supplied operand

### ISSUE THREAD

**Issue by net-wayfarer** [arch-community/qbot#77]
This is a feature request from observing phrik (#archlinux IRC bot). To demonstrate what the feature requests meant, please refer to the following below,
```
<Sophon> !give rain AUR
<phrik> rain, https://wiki.archlinux.org/index.php/Arch_User_Repository
```

**Comment by anna328p** [comment]
On IRC this would be the correct method. I'd want to do it differently on Discord.

I could have the bot reply-ping (or just mention) a specified user.

**Comment by anna328p** [comment]
wontfix
