### ISSUE TITLE
`my_repo` in example config outdated

### ISSUE THREAD

**Issue by FjorgeTheHuman** [arch-community/qbot#78]
It still points to the old pre-organisation link (https://github.com/anna328p/qbot) instead of pointing to the new link (https://github.com/arch-community/qbot).
This is also present in the qbot instance hosted by the owner

**Comment by Sophon96** [comment]
`roles.rb` is blank, which causes an error when launching the bot with the default config. Should it be removed as well?

**Comment by anna328p** [comment]
Yes
